### ISSUE TITLE
Home page button text is not v.aligned

### ISSUE THREAD

**Issue by fozcode** [qisphotos/qisphotos.github.io#37]
The text in the FREE STANDARD EDITION button is not vertically centered, while the text in all the other buttons is.

**Comment by qururoland** [comment]
Tried all sorts of vertical alignment. In the end added a _"display: relative; bottom: 3px;"_ combo to the text element (seems odd to do all this as list elements but there you go) and it aligns when at normal font size. Because the github icon is a logo, if the zoom is set to "text only" in the browser, then zooming breaks the alignment - there again, it breaks the whole page layout so....
